/* generated by mediatek */

package com.gionee.featureoption;

public final class FeatureOption {
    /**
     * check if GN_APK_ADD_PROFILE is turned on or not
     */
    public static final boolean GN_APK_ADD_PROFILE = true;
    /**
     * check if GN_APK_PUBLIC_JAR is turned on or not
     */
    public static final boolean GN_APK_PUBLIC_JAR = true;
}
